name: PR Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Test
        run: dotnet build --configuration Release
        env:
          NUGET_VERSION: ${{ github.run_number }}

#      - name: Run Tests
#        run: dotnet test --no-build --configuration Release
